<a href="https://colab.research.google.com/github/preranajana2007-art/blackjackgame/blob/main/prerana_b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
print("prerana")

prerana

In [10]:
print(type(11))
print(type(11.0))
print(type('11'))
print(type(True))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>

In [14]:

# here we are printing hello

In [19]:
print(float(11))

11.0

In [22]:
print(int(11.11))

11

In [24]:
print(type(int('11')))

<class 'int'>

In [164]:
print(int("A"))

ValueError: invalid literal for int() with base 10: 'A'

In [30]:
print(type(bool(1)))

<class 'bool'>

In [32]:
print(10+5)
print(10-20)
print(5*5)
print(25/5)

15
-10
25
5.0

In [35]:
print(25/6) #normal division
print(25//6) #integer division
print(-21/6)
print(-21//6) #task

4.166666666666667
4
-3.5
-4

In [39]:
print(10+5*2)
print((10+5)*2)

20
30

In [42]:
X=10 # X is storing the value 10.
print(X)

10

In [44]:
X=10
X=20 #Latest value replaces the old one.
print(X)

20

In [47]:
X=10+5 #Variables can store results also
print(X)

15

In [52]:
X = 10
Y  = 5
result =(X+Y)*2
print(result)

30

In [57]:
english=34
math=29
bengali=36
totalmarks =english+math+bengali
print(totalmarks)
persentage=(totalmarks*3)/100
print(persentage)

99
2.97

In [60]:
name=input("Enter name :")
print(name)

Enter name :prer
prer

In [63]:
age =int(input("Enter your age:"))
print(type(age))
print(age+4)

Enter your age:56
<class 'int'>
60

In [66]:
name="michanel jackson"
print(type(name))
print(len(name))

<class 'str'>
16

In [71]:
name[1:10:2]
name[::-2]

'nscjlnhi'

In [74]:
name="prerana"
name[2:4]

'er'

In [80]:
name="prerana"
name[::-3]

'arp'

In [82]:
len(name)

7

In [85]:
comliment=name+"is the best"
print('compliment')

compliment

In [88]:
name = "prerana"
print(name.capitalize())

Prerana

In [90]:
print("C:\\users\\prerana")

C:\users\prerana

In [98]:
#star.format
name="prer"
age="23"

print(f"My name is{name}and my age is {age}.")

My name isprerand my age is 23.

In [139]:

marks = int(input("Enter your marks:"))
if marks>=80:
     print("A");
elif marks>=60:
     print("B");
else:
      print("C");

Enter your marks:56
C

In [142]:
total = 0
x=int(input("Enter the number :"))
for i in range(1,X):
   total=total=1
   print("total:",total)

Enter the number :5
total: 1
total: 1
total: 1
total: 1
total: 1
total: 1
total: 1
total: 1
total: 1

In [145]:
i=1
while i<=11:
  print(i)
  i=i+3

1
4
7
10

In [163]:
for i in range(1,10):
  if i == 3:
    continue
  if i == 5:
      break
  print(i)

1
2
4

In [166]:
print("start")
def greet():
  print("Hello")

greet()

print("End")

start
Hello
End

In [174]:
# parameter and argument
def greet(name):
  print("hello",name)

greet("prerana")
 #name-parameter, prerana-argument

hello prerana

In [3]:
def add(a,b):
 '''

this function adds 2 Number

 '''

 return a+b
result=add(2,3)
help(add)
print(result)

Help on function add in module __main__:

add(a, b)
    this function adds 2 Number

5

In [9]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]

In [11]:
list[0] = 15
print(list)

[15, 2, 3, 4]

In [17]:
fruits = ["apple","banana","mango"]
mixed = [10,"hello",3.5,True]
print(fruits)
print(mixed)
type(fruits)

['apple', 'banana', 'mango']
[10, 'hello', 3.5, True]

list

In [19]:
fruits = ["apple", "banana", "mango"]
fruits[1] ="orange"
print(fruits)

['apple', 'orange', 'mango']

In [24]:
lst = [10,20,30,40,50,60,70]
print(lst[1:4])

[20, 30, 40]

In [26]:
print(lst[::2])

[10, 30, 50, 70]

In [28]:
print(lst[-4:-1])

[40, 50, 60]

In [30]:
print(lst[::-1])

[70, 60, 50, 40, 30, 20, 10]

In [33]:
#question
#Question 1: Reverse and Extract only first 3 element
lst =[5,10,15,20,25,30]
list=lst[::-1]
print(lst[-4:-1])

[15, 20, 25]

In [34]:
lst = [1,2,3,4,5,6,7,8]
even_index = lst[::2]
odd_index = lst[1::2]
print("Even index list:",even_index)
print("Odd index list:",odd_index)

Even index list: [1, 3, 5, 7]
Odd index list: [2, 4, 6, 8]

In [37]:
# 1 append()
# Adds one elements at the end
lst = [1,2,3]
print(lst)
lst.append(4)
print(lst)

[1, 2, 3]
[1, 2, 3, 4]

In [39]:
# 4 remove()
lst.remove(4)
print(lst)

[1, 2]

In [40]:
# 6 clear()
lst = [1,2,3]
lst.clear()
print(lst)

[]

In [42]:
# 7 searching & conting
#index()
# returns index of element
lst=[10,20,30]
print(lst.index(30))

2

In [43]:
# 9 sort()
lst = [3,2,1]
lst.sort()
print(lst)

[1, 2, 3]

In [46]:
# 10 revers()
lst = [1,2,3]
lst.reverse()
print(lst)

[3, 2, 1]

TUPLE

In [48]:
t = (5)
#t = (5,)
t1 = (1,2,3)
t2=("a","b","c","d")
print(t1)
print(t2)

(1, 2, 3)
('a', 'b', 'c', 'd')

In [52]:

#tupple method
t =(1,2,3,4,5,2,2,2)
x=t.index(2)
print(x)

1

dictionary

In [57]:
xy={
    "name":"prerana"
  }
print(type(xy))
xy["word"]="meaning"
print(xy)

<class 'dict'>
{'name': 'prerana', 'word': 'meaning'}

In [66]:
dic ={
    "name":"aditi",
    "subjects" :["python","c","java"],
    "age" :21,
    "is adult":True,
    "topics":("dict","set")
}
print(dic,"\n")

print(dic["name"])
print(dic["age"])
print(dic["subjects"])

{'name': 'aditi', 'subjects': ['python', 'c', 'java'], 'age': 21, 'is adult': True, 'topics': ('dict', 'set')}

aditi
21
['python', 'c', 'java']

In [72]:
student = {
    "name":"anu",
    "subjects" :{
          "phy":99,
          "math":89,
          "che":79
    },
    "age" :21,
    "dep":"BT",
    "topics":("dict","set")
}
print(student )
print(student["subjects"])
print(student["subjects"]["che"])

{'name': 'anu', 'subjects': {'phy': 99, 'math': 89, 'che': 79}, 'age': 21, 'dep': 'BT', 'topics': ('dict', 'set')}
{'phy': 99, 'math': 89, 'che': 79}
79

SET

In [74]:
#2update()
#adds multiple elements
s1={1,2}
print(s1)
s1.update([3,4,5,"sy"])
print("s1=",s1)

{1, 2}
s1= {1, 2, 3, 4, 5, 'sy'}

In [78]:
a={1,2,3}
b={3,4,5}
print(a.union(b))
print(a.intersection(b))
print(b.difference(a))

{1, 2, 3, 4, 5}
{3}
{4, 5}

In [90]:
import pandas as pd

In [91]:
s =pd.Series([1,2,3,4,5, 23,35,56])
print(s)
print(type(s))

0     1
1     2
2     3
3     4
4     5
5    23
6    35
7    56
dtype: int64
<class 'pandas.core.series.Series'>

In [92]:
s.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [99]:
# reading a csv file
df =pd.read_csv("student-data.csv")
print(df)

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... internet romantic  famrel  freetime  goout Dalc Walc health absences  \
0    ...       no       no       4         3      4    1    1      3        6
1    ...      yes       no       5         3      3    1    1      3        4
2    ...      yes       no       4         3      2    2    3      3       10
3    ...      yes      yes       3         2      2    1    1      5        2
4    ...       no       no       4         3      2    1    2      5        4
..   ...      ...      ...     ...       ...    ...  ...  ...    ...      ...
390  ...       no       no       5         5      4    4    5      4       11
391  ...      yes       no       2         4      5    3    4      2        3
392  ...       no       no       5         5      3    3    3      3        3
393  ...      yes       no       4         4      1    3    4      5        0
394  ...      yes       no       3         2      3    3    3      5        5

    passed
0       no
1       no
2      yes
3      yes
4      yes
..     ...
390     no
391    yes
392     no
393    yes
394     no

[395 rows x 31 columns]

In [102]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes

In [104]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  passed      395 non-null    object
dtypes: int64(13), object(18)
memory usage: 95.8+ KB

In [108]:
df.shape

(395, 31)

In [110]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [111]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000

In [112]:
df["age"]

0      18
1      17
2      15
3      15
4      16
       ..
390    20
391    17
392    21
393    18
394    19
Name: age, Length: 395, dtype: int64

In [114]:
df.iloc[0:3]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes

In [119]:
df.loc[0:2,["age"]]

   age
0   18
1   17
2   15

In [121]:
df.dropna()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,no
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,no
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,yes
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,yes
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,no,no,5,5,4,4,5,4,11,no
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,no,2,4,5,3,4,2,3,yes
392,MS,M,21,R,GT3,T,1,1,other,other,...,no,no,5,5,3,3,3,3,3,no
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,no,4,4,1,3,4,5,0,yes
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,no,3,2,3,3,3,5,5,no

In [122]:
df.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,passed
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
import numpy as np

In [124]:
#list
a=[1,"pre",2.3454,"ahana"]
print(a)

[1, 'pre', 2.3454, 'ahana']

In [125]:
x=np.array(a)
print("\n",x)

 ['1' 'pre' '2.3454' 'ahana']

In [134]:
b =np.array([[1,2,34],
           [2,4,6]])
b.shape

(2, 3)

import random

In [35]:
import random

In [36]:
card_categories =['Hearts','Diamonds','clubs','Spades']
cards_list = ['Ace','2','3','4','5','6','7','8','9','10','Jack','Queen','King']
deck = [(card,category) for category in card_categories for card in cards_list]

In [37]:
def card_value(card):
  if card[0] in ['jack','queen','King']:
    return 10
  elif card[0] =='Ace':
      return 11
  else:
        return int(card[0])

In [38]:
#We will use random.shuffle() to shuffle our deck of cards to maintain randomness
random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]

In [43]:
while True:
  player_score = sum(card_value(card) for card in player_card)
  dealer_score = sum(card_value(card) for card in dealer_card)
  print("cards player Has:",player_card)
  print("score of The player:",player_score)
  print("\n")
  choice = input('What do you want? ["play"to request another card, "stop" to stop]):').lower()
  if choice == "play":
   new_card = deck.pop()
   player_card.append(new_card)
  elif choice =="stop":
    break
  else:
    print("Invalid chioce.Please try again.")
    continue
    if player_score>21:
      print("cards Dealer Has:",dealer_card)
      print("score of The Dealer:",dealer_score)
      print("cards player Has:",player_card)
      print("Score of The player:",player_score)
      print("Dealer wins (player Loss Beacuse Player Score is exceeding 21)")
      break

cards player Has: [('2', 'Spades'), ('Ace', 'Spades'), ('Ace', 'Diamonds')]
score of The player: 24


What do you want? ["play"to request another card, "stop" to stop]):stop

In [40]:
#dealer has to draw cards now
while dealer_score < 17:
    new_card = deck.pop()
    dealer_card.append(new_card)
    dealer_score += card_value(new_card)

print("Cards Dealer Has:", dealer_card)
print("Score Of The Dealer:", dealer_score)
print("\n")

Cards Dealer Has: [('10', 'Spades'), ('4', 'Diamonds'), ('7', 'Hearts')]
Score Of The Dealer: 21

In [41]:
#decision wala code hai ye omggg who will win guess karna
if dealer_score > 21:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)")
elif player_score > dealer_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Player wins (Player Has High Score than Dealer)")
elif dealer_score > player_score:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("Dealer wins (Dealer Has High Score than Player)")
else:
    print("Cards Dealer Has:", dealer_card)
    print("Score Of The Dealer:", dealer_score)
    print("Cards Player Has:", player_card)
    print("Score Of The Player:", player_score)
    print("It's a tie.")

Cards Dealer Has: [('10', 'Spades'), ('4', 'Diamonds'), ('7', 'Hearts')]
Score Of The Dealer: 21
Cards Player Has: [('2', 'Spades'), ('Ace', 'Spades'), ('Ace', 'Diamonds')]
Score Of The Player: 24
Player wins (Player Has High Score than Dealer)